version: '3.7'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: fake_password
      POSTGRES_DB: logger
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  log_service:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file: ./.env

volumes:
  postgres-data:
